---
driver:
  name: vagrant

platforms:
  - name: centos7-64
    driver_config:
      box: rchrd/centos-7-x64-salt

provisioner:
  name: salt_solo
  salt_version: 2015.8.8
  data_path: test/shared
  is_file_root: true
  pillars:
    top.sls:
      base:
        '*':
          - mirth
    mirth.sls:
      mirth:
        - pkg: mirthconnect

suites:
  - name: mirth_install
    provisioner:
      state_top:
        base:
          '*':
            - mirth
