---
driver:
  name: vagrant

platforms:
  - name: centos7-64
    driver_config:
      box: rchrd/centos-7-x64-salt

provisioner:
  name: salt_solo
  salt_version: 2016.3.2
  data_path: test/shared
  log_level: debug
  is_file_root: true
  pillars:
    top.sls:
      base:
        '*':
          - mirth

suites:
  - name: mirth_install
    provisioner:
      pillars-from-files:
        mirth.sls: mirth/defaults.yaml
      state_top:
        base:
          '*':
            - mirth
  - name: mirth_config
    provisioner:
      pillars-from-files:
        mirth.sls: pillar.example
      state_top:
        base:
          '*':
            - mirth
            - mirth.config
